// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta3/model_service.proto
// </auto-generated>
// Original file comments:
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Google.Ai.Generativelanguage.V1Beta3 {
  /// <summary>
  /// Provides methods for getting metadata information about Generative Models.
  /// </summary>
  public static partial class ModelService
  {
    static readonly string __ServiceName = "google.ai.generativelanguage.v1beta3.ModelService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest> __Marshaller_google_ai_generativelanguage_v1beta3_GetModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.Model> __Marshaller_google_ai_generativelanguage_v1beta3_Model = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.Model.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest> __Marshaller_google_ai_generativelanguage_v1beta3_ListModelsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse> __Marshaller_google_ai_generativelanguage_v1beta3_ListModelsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest> __Marshaller_google_ai_generativelanguage_v1beta3_GetTunedModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> __Marshaller_google_ai_generativelanguage_v1beta3_TunedModel = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest> __Marshaller_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse> __Marshaller_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest> __Marshaller_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.LongRunning.Operation> __Marshaller_google_longrunning_Operation = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.LongRunning.Operation.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest> __Marshaller_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest> __Marshaller_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.Model> __Method_GetModel = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.Model>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetModel",
        __Marshaller_google_ai_generativelanguage_v1beta3_GetModelRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_Model);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse> __Method_ListModels = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListModels",
        __Marshaller_google_ai_generativelanguage_v1beta3_ListModelsRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_ListModelsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> __Method_GetTunedModel = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTunedModel",
        __Marshaller_google_ai_generativelanguage_v1beta3_GetTunedModelRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_TunedModel);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse> __Method_ListTunedModels = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListTunedModels",
        __Marshaller_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest, global::Google.LongRunning.Operation> __Method_CreateTunedModel = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest, global::Google.LongRunning.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateTunedModel",
        __Marshaller_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest,
        __Marshaller_google_longrunning_Operation);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> __Method_UpdateTunedModel = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateTunedModel",
        __Marshaller_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_TunedModel);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteTunedModel = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTunedModel",
        __Marshaller_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Ai.Generativelanguage.V1Beta3.ModelServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ModelService</summary>
    [grpc::BindServiceMethod(typeof(ModelService), "BindService")]
    public abstract partial class ModelServiceBase
    {
      /// <summary>
      /// Gets information about a specific Model.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.Model> GetModel(global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Lists models available through the API.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse> ListModels(global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Gets information about a specific TunedModel.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> GetTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Lists tuned models owned by the user.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse> ListTunedModels(global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Creates a tuned model.
      /// Intermediate tuning progress (if any) is accessed through the
      /// [google.longrunning.Operations] service.
      ///
      /// Status and results can be accessed through the Operations service.
      /// Example:
      ///   GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.LongRunning.Operation> CreateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Updates a tuned model.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> UpdateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Deletes a tuned model.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ModelService</summary>
    public partial class ModelServiceClient : grpc::ClientBase<ModelServiceClient>
    {
      /// <summary>Creates a new client for ModelService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ModelServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ModelService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ModelServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ModelServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ModelServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Gets information about a specific Model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.Model GetModel(global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets information about a specific Model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.Model GetModel(global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetModel, null, options, request);
      }
      /// <summary>
      /// Gets information about a specific Model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.Model> GetModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets information about a specific Model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.Model> GetModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetModel, null, options, request);
      }
      /// <summary>
      /// Lists models available through the API.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse ListModels(global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListModels(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists models available through the API.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse ListModels(global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListModels, null, options, request);
      }
      /// <summary>
      /// Lists models available through the API.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse> ListModelsAsync(global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListModelsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists models available through the API.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse> ListModelsAsync(global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListModels, null, options, request);
      }
      /// <summary>
      /// Gets information about a specific TunedModel.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.TunedModel GetTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTunedModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets information about a specific TunedModel.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.TunedModel GetTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTunedModel, null, options, request);
      }
      /// <summary>
      /// Gets information about a specific TunedModel.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> GetTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTunedModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets information about a specific TunedModel.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> GetTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTunedModel, null, options, request);
      }
      /// <summary>
      /// Lists tuned models owned by the user.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse ListTunedModels(global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListTunedModels(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists tuned models owned by the user.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse ListTunedModels(global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListTunedModels, null, options, request);
      }
      /// <summary>
      /// Lists tuned models owned by the user.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse> ListTunedModelsAsync(global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListTunedModelsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists tuned models owned by the user.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse> ListTunedModelsAsync(global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListTunedModels, null, options, request);
      }
      /// <summary>
      /// Creates a tuned model.
      /// Intermediate tuning progress (if any) is accessed through the
      /// [google.longrunning.Operations] service.
      ///
      /// Status and results can be accessed through the Operations service.
      /// Example:
      ///   GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.LongRunning.Operation CreateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTunedModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates a tuned model.
      /// Intermediate tuning progress (if any) is accessed through the
      /// [google.longrunning.Operations] service.
      ///
      /// Status and results can be accessed through the Operations service.
      /// Example:
      ///   GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.LongRunning.Operation CreateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTunedModel, null, options, request);
      }
      /// <summary>
      /// Creates a tuned model.
      /// Intermediate tuning progress (if any) is accessed through the
      /// [google.longrunning.Operations] service.
      ///
      /// Status and results can be accessed through the Operations service.
      /// Example:
      ///   GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.LongRunning.Operation> CreateTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTunedModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates a tuned model.
      /// Intermediate tuning progress (if any) is accessed through the
      /// [google.longrunning.Operations] service.
      ///
      /// Status and results can be accessed through the Operations service.
      /// Example:
      ///   GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.LongRunning.Operation> CreateTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTunedModel, null, options, request);
      }
      /// <summary>
      /// Updates a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.TunedModel UpdateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTunedModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.TunedModel UpdateTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateTunedModel, null, options, request);
      }
      /// <summary>
      /// Updates a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> UpdateTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTunedModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.TunedModel> UpdateTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateTunedModel, null, options, request);
      }
      /// <summary>
      /// Deletes a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTunedModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTunedModel(global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteTunedModel, null, options, request);
      }
      /// <summary>
      /// Deletes a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTunedModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a tuned model.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTunedModelAsync(global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteTunedModel, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ModelServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ModelServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ModelServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetModel, serviceImpl.GetModel)
          .AddMethod(__Method_ListModels, serviceImpl.ListModels)
          .AddMethod(__Method_GetTunedModel, serviceImpl.GetTunedModel)
          .AddMethod(__Method_ListTunedModels, serviceImpl.ListTunedModels)
          .AddMethod(__Method_CreateTunedModel, serviceImpl.CreateTunedModel)
          .AddMethod(__Method_UpdateTunedModel, serviceImpl.UpdateTunedModel)
          .AddMethod(__Method_DeleteTunedModel, serviceImpl.DeleteTunedModel).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ModelServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.GetModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.Model>(serviceImpl.GetModel));
      serviceBinder.AddMethod(__Method_ListModels, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.ListModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListModelsResponse>(serviceImpl.ListModels));
      serviceBinder.AddMethod(__Method_GetTunedModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.GetTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel>(serviceImpl.GetTunedModel));
      serviceBinder.AddMethod(__Method_ListTunedModels, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsRequest, global::Google.Ai.Generativelanguage.V1Beta3.ListTunedModelsResponse>(serviceImpl.ListTunedModels));
      serviceBinder.AddMethod(__Method_CreateTunedModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.CreateTunedModelRequest, global::Google.LongRunning.Operation>(serviceImpl.CreateTunedModel));
      serviceBinder.AddMethod(__Method_UpdateTunedModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.UpdateTunedModelRequest, global::Google.Ai.Generativelanguage.V1Beta3.TunedModel>(serviceImpl.UpdateTunedModel));
      serviceBinder.AddMethod(__Method_DeleteTunedModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.DeleteTunedModelRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteTunedModel));
    }

  }
}
#endregion
