// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta3/permission.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ai.Generativelanguage.V1Beta3 {

  /// <summary>Holder for reflection information generated from google/ai/generativelanguage/v1beta3/permission.proto</summary>
  public static partial class PermissionReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ai/generativelanguage/v1beta3/permission.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PermissionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVnb29nbGUvYWkvZ2VuZXJhdGl2ZWxhbmd1YWdlL3YxYmV0YTMvcGVybWlz",
            "c2lvbi5wcm90bxIkZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52MWJl",
            "dGEzGh9nb29nbGUvYXBpL2ZpZWxkX2JlaGF2aW9yLnByb3RvGhlnb29nbGUv",
            "YXBpL3Jlc291cmNlLnByb3RvIrAECgpQZXJtaXNzaW9uEhEKBG5hbWUYASAB",
            "KAlCA+BBAxJfCgxncmFudGVlX3R5cGUYAiABKA4yPC5nb29nbGUuYWkuZ2Vu",
            "ZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTMuUGVybWlzc2lvbi5HcmFudGVlVHlw",
            "ZUIG4EEC4EEFSACIAQESIgoNZW1haWxfYWRkcmVzcxgDIAEoCUIG4EEB4EEF",
            "SAGIAQESTQoEcm9sZRgEIAEoDjI1Lmdvb2dsZS5haS5nZW5lcmF0aXZlbGFu",
            "Z3VhZ2UudjFiZXRhMy5QZXJtaXNzaW9uLlJvbGVCA+BBAkgCiAEBIk4KC0dy",
            "YW50ZWVUeXBlEhwKGEdSQU5URUVfVFlQRV9VTlNQRUNJRklFRBAAEggKBFVT",
            "RVIQARIJCgVHUk9VUBACEgwKCEVWRVJZT05FEAMiPwoEUm9sZRIUChBST0xF",
            "X1VOU1BFQ0lGSUVEEAASCQoFT1dORVIQARIKCgZXUklURVIQAhIKCgZSRUFE",
            "RVIQAzp+6kF7CixnZW5lcmF0aXZlbGFuZ3VhZ2UuZ29vZ2xlYXBpcy5jb20v",
            "UGVybWlzc2lvbhIydHVuZWRNb2RlbHMve3R1bmVkX21vZGVsfS9wZXJtaXNz",
            "aW9ucy97cGVybWlzc2lvbn0qC3Blcm1pc3Npb25zMgpwZXJtaXNzaW9uQg8K",
            "DV9ncmFudGVlX3R5cGVCEAoOX2VtYWlsX2FkZHJlc3NCBwoFX3JvbGVCnQEK",
            "KGNvbS5nb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YTNCD1Bl",
            "cm1pc3Npb25Qcm90b1ABWl5jbG91ZC5nb29nbGUuY29tL2dvL2FpL2dlbmVy",
            "YXRpdmVsYW5ndWFnZS9hcGl2MWJldGEzL2dlbmVyYXRpdmVsYW5ndWFnZXBi",
            "O2dlbmVyYXRpdmVsYW5ndWFnZXBiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ai.Generativelanguage.V1Beta3.Permission), global::Google.Ai.Generativelanguage.V1Beta3.Permission.Parser, new[]{ "Name", "GranteeType", "EmailAddress", "Role" }, new[]{ "GranteeType", "EmailAddress", "Role" }, new[]{ typeof(global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType), typeof(global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Permission resource grants user, group or the rest of the world access to the
  /// PaLM API resource (e.g. a tuned model, file).
  ///
  /// A role is a collection of permitted operations that allows users to perform
  /// specific actions on PaLM API resources. To make them available to users,
  /// groups, or service accounts, you assign roles. When you assign a role, you
  /// grant permissions that the role contains.
  ///
  /// There are three concentric roles. Each role is a superset of the previous
  /// role's permitted operations:
  ///  - reader can use the resource (e.g. tuned model) for inference
  ///  - writer has reader's permissions and additionally can edit and share
  ///  - owner has writer's permissions and additionally can delete
  /// </summary>
  public sealed partial class Permission : pb::IMessage<Permission>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Permission> _parser = new pb::MessageParser<Permission>(() => new Permission());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Permission> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ai.Generativelanguage.V1Beta3.PermissionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Permission() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Permission(Permission other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      granteeType_ = other.granteeType_;
      emailAddress_ = other.emailAddress_;
      role_ = other.role_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Permission Clone() {
      return new Permission(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Output only. The permission name. A unique name will be generated on
    /// create. Example: tunedModels/{tuned_model}permssions/{permission} Output
    /// only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grantee_type" field.</summary>
    public const int GranteeTypeFieldNumber = 2;
    private readonly static global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType GranteeTypeDefaultValue = global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType.Unspecified;

    private global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType granteeType_;
    /// <summary>
    /// Required. Immutable. The type of the grantee.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType GranteeType {
      get { if ((_hasBits0 & 1) != 0) { return granteeType_; } else { return GranteeTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        granteeType_ = value;
      }
    }
    /// <summary>Gets whether the "grantee_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGranteeType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "grantee_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGranteeType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "email_address" field.</summary>
    public const int EmailAddressFieldNumber = 3;
    private readonly static string EmailAddressDefaultValue = "";

    private string emailAddress_;
    /// <summary>
    /// Optional. Immutable. The email address of the user of group which this
    /// permission refers. Field is not set when permission's grantee type is
    /// EVERYONE.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EmailAddress {
      get { return emailAddress_ ?? EmailAddressDefaultValue; }
      set {
        emailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "email_address" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEmailAddress {
      get { return emailAddress_ != null; }
    }
    /// <summary>Clears the value of the "email_address" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEmailAddress() {
      emailAddress_ = null;
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 4;
    private readonly static global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role RoleDefaultValue = global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role.Unspecified;

    private global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role role_;
    /// <summary>
    /// Required. The role granted by this permission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role Role {
      get { if ((_hasBits0 & 2) != 0) { return role_; } else { return RoleDefaultValue; } }
      set {
        _hasBits0 |= 2;
        role_ = value;
      }
    }
    /// <summary>Gets whether the "role" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRole {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "role" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRole() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Permission);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Permission other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (GranteeType != other.GranteeType) return false;
      if (EmailAddress != other.EmailAddress) return false;
      if (Role != other.Role) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (HasGranteeType) hash ^= GranteeType.GetHashCode();
      if (HasEmailAddress) hash ^= EmailAddress.GetHashCode();
      if (HasRole) hash ^= Role.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasGranteeType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GranteeType);
      }
      if (HasEmailAddress) {
        output.WriteRawTag(26);
        output.WriteString(EmailAddress);
      }
      if (HasRole) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Role);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasGranteeType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GranteeType);
      }
      if (HasEmailAddress) {
        output.WriteRawTag(26);
        output.WriteString(EmailAddress);
      }
      if (HasRole) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Role);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasGranteeType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GranteeType);
      }
      if (HasEmailAddress) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EmailAddress);
      }
      if (HasRole) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Role);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Permission other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.HasGranteeType) {
        GranteeType = other.GranteeType;
      }
      if (other.HasEmailAddress) {
        EmailAddress = other.EmailAddress;
      }
      if (other.HasRole) {
        Role = other.Role;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            GranteeType = (global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType) input.ReadEnum();
            break;
          }
          case 26: {
            EmailAddress = input.ReadString();
            break;
          }
          case 32: {
            Role = (global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            GranteeType = (global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.GranteeType) input.ReadEnum();
            break;
          }
          case 26: {
            EmailAddress = input.ReadString();
            break;
          }
          case 32: {
            Role = (global::Google.Ai.Generativelanguage.V1Beta3.Permission.Types.Role) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Permission message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Defines types of the grantee of this permission.
      /// </summary>
      public enum GranteeType {
        /// <summary>
        /// The default value. This value is unused.
        /// </summary>
        [pbr::OriginalName("GRANTEE_TYPE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Represents a user. When set, you must provide email_address for the user.
        /// </summary>
        [pbr::OriginalName("USER")] User = 1,
        /// <summary>
        /// Represents a group. When set, you must provide email_address for the
        /// group.
        /// </summary>
        [pbr::OriginalName("GROUP")] Group = 2,
        /// <summary>
        /// Represents access to everyone. No extra information is required.
        /// </summary>
        [pbr::OriginalName("EVERYONE")] Everyone = 3,
      }

      /// <summary>
      /// Defines the role granted by this permission.
      /// </summary>
      public enum Role {
        /// <summary>
        /// The default value. This value is unused.
        /// </summary>
        [pbr::OriginalName("ROLE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Owner can use, update, share and delete the resource.
        /// </summary>
        [pbr::OriginalName("OWNER")] Owner = 1,
        /// <summary>
        /// Writer can use, update and share the resource.
        /// </summary>
        [pbr::OriginalName("WRITER")] Writer = 2,
        /// <summary>
        /// Reader can use the resource.
        /// </summary>
        [pbr::OriginalName("READER")] Reader = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
