// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ai/generativelanguage/v1beta3/text_service.proto
// </auto-generated>
// Original file comments:
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Google.Ai.Generativelanguage.V1Beta3 {
  /// <summary>
  /// API for using Generative Language Models (GLMs) trained to generate text.
  ///
  /// Also known as Large Language Models (LLM)s, these generate text given an
  /// input prompt from the user.
  /// </summary>
  public static partial class TextService
  {
    static readonly string __ServiceName = "google.ai.generativelanguage.v1beta3.TextService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest> __Marshaller_google_ai_generativelanguage_v1beta3_GenerateTextRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse> __Marshaller_google_ai_generativelanguage_v1beta3_GenerateTextResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest> __Marshaller_google_ai_generativelanguage_v1beta3_EmbedTextRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse> __Marshaller_google_ai_generativelanguage_v1beta3_EmbedTextResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest> __Marshaller_google_ai_generativelanguage_v1beta3_BatchEmbedTextRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse> __Marshaller_google_ai_generativelanguage_v1beta3_BatchEmbedTextResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest> __Marshaller_google_ai_generativelanguage_v1beta3_CountTextTokensRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse> __Marshaller_google_ai_generativelanguage_v1beta3_CountTextTokensResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse> __Method_GenerateText = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateText",
        __Marshaller_google_ai_generativelanguage_v1beta3_GenerateTextRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_GenerateTextResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse> __Method_EmbedText = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EmbedText",
        __Marshaller_google_ai_generativelanguage_v1beta3_EmbedTextRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_EmbedTextResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse> __Method_BatchEmbedText = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchEmbedText",
        __Marshaller_google_ai_generativelanguage_v1beta3_BatchEmbedTextRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_BatchEmbedTextResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest, global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse> __Method_CountTextTokens = new grpc::Method<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest, global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CountTextTokens",
        __Marshaller_google_ai_generativelanguage_v1beta3_CountTextTokensRequest,
        __Marshaller_google_ai_generativelanguage_v1beta3_CountTextTokensResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Ai.Generativelanguage.V1Beta3.TextServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TextService</summary>
    [grpc::BindServiceMethod(typeof(TextService), "BindService")]
    public abstract partial class TextServiceBase
    {
      /// <summary>
      /// Generates a response from the model given an input message.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse> GenerateText(global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates an embedding from the model given an input message.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse> EmbedText(global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates multiple embeddings from the model given input text in a
      /// synchronous call.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse> BatchEmbedText(global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Runs a model's tokenizer on a text and returns the token count.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse> CountTextTokens(global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TextService</summary>
    public partial class TextServiceClient : grpc::ClientBase<TextServiceClient>
    {
      /// <summary>Creates a new client for TextService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TextServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TextService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TextServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TextServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TextServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Generates a response from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse GenerateText(global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateText(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a response from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse GenerateText(global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateText, null, options, request);
      }
      /// <summary>
      /// Generates a response from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse> GenerateTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateTextAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a response from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse> GenerateTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateText, null, options, request);
      }
      /// <summary>
      /// Generates an embedding from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse EmbedText(global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EmbedText(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates an embedding from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse EmbedText(global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EmbedText, null, options, request);
      }
      /// <summary>
      /// Generates an embedding from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse> EmbedTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EmbedTextAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates an embedding from the model given an input message.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse> EmbedTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EmbedText, null, options, request);
      }
      /// <summary>
      /// Generates multiple embeddings from the model given input text in a
      /// synchronous call.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse BatchEmbedText(global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchEmbedText(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates multiple embeddings from the model given input text in a
      /// synchronous call.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse BatchEmbedText(global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchEmbedText, null, options, request);
      }
      /// <summary>
      /// Generates multiple embeddings from the model given input text in a
      /// synchronous call.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse> BatchEmbedTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchEmbedTextAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates multiple embeddings from the model given input text in a
      /// synchronous call.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse> BatchEmbedTextAsync(global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchEmbedText, null, options, request);
      }
      /// <summary>
      /// Runs a model's tokenizer on a text and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse CountTextTokens(global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CountTextTokens(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Runs a model's tokenizer on a text and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse CountTextTokens(global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CountTextTokens, null, options, request);
      }
      /// <summary>
      /// Runs a model's tokenizer on a text and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse> CountTextTokensAsync(global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CountTextTokensAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Runs a model's tokenizer on a text and returns the token count.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse> CountTextTokensAsync(global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CountTextTokens, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TextServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TextServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TextServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GenerateText, serviceImpl.GenerateText)
          .AddMethod(__Method_EmbedText, serviceImpl.EmbedText)
          .AddMethod(__Method_BatchEmbedText, serviceImpl.BatchEmbedText)
          .AddMethod(__Method_CountTextTokens, serviceImpl.CountTextTokens).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TextServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GenerateText, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.GenerateTextResponse>(serviceImpl.GenerateText));
      serviceBinder.AddMethod(__Method_EmbedText, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.EmbedTextResponse>(serviceImpl.EmbedText));
      serviceBinder.AddMethod(__Method_BatchEmbedText, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextRequest, global::Google.Ai.Generativelanguage.V1Beta3.BatchEmbedTextResponse>(serviceImpl.BatchEmbedText));
      serviceBinder.AddMethod(__Method_CountTextTokens, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensRequest, global::Google.Ai.Generativelanguage.V1Beta3.CountTextTokensResponse>(serviceImpl.CountTextTokens));
    }

  }
}
#endregion
